name: afib_firebase_firestore
description: A starting point for Dart libraries or applications.
version: 0.5.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  meta: ^1.9.1
  afib: # ^0.5.0
    path: /Users/chrisjones/projects/afib/afib
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0


dev_dependencies:
  flutter_lints: ^2.0.2
  test: ^1.24.6