name: afib_firebase_firestore
description: An AFib-aware package that adds command-line options for creating AFib queries that interact with Firestore
homepage: https://www.afibframework.io
repository: https://github.com/chrisjones314/afib_firebase_firestore
issue_tracker: https://github.com/chrisjones314/afib_firebase_firestore/issues
documentation: https://docs.afibframework.io/v0.5/afib_firebase_firestore/startup/start_here/

version: 0.5.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  afib: #^0.5.2
    path: /Users/chrisjones/projects/afib/afib
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.24.3