name: afib_firebase_firestore
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  meta: ^1.9.1
  afib:
    path: /Users/chrisjones/projects/afib/afib
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0